spring:
  application:
    name: stock-dividends

  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    defer-datasource-initialization: true

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:stock-dividends;DB_CLOSE_DELAY=-1
    username: sa
    password:

  data:
    redis:
      port: 6379
      host: localhost

scheduler:
  scrap:
    yahoo: "0 0 0 * * *"


