spring:
  application:
    name: stock-dividends

  h2:
    console:
      enabled: true
      path: /data/h2/console

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    defer-datasource-initialization: true

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:stock-dividends;DB_CLOSE_DELAY=-1
    username: sa
    password:

